    name: Testing

    
    on:
      workflow_dispatch:
        inputs:
          selected_options:
            description: 'Choose options to process'
            type: choice
            options:
              - Option A
              - Option B
              - Option C
              - All
            required: true

    jobs:
      loop-through-choices:
        runs-on: ubuntu-latest
        steps:
          - name: Get code
            uses: actions/checkout@v3
          - name: invoke
            run: |
                ls -d */ >myfile.txt
                cat myfile.txt
          - name: Iterate over All selected options
            if: ${{ github.event.inputs.selected_options == 'All' }}
            run: |
              selected_options="optionA,optionB,optionC"
              IFS=',' read -r -a array <<< "$selected_options"
              for item in "${array[@]}"; do
                echo "Processing $item"
                # Perform actions based on the current item
              done

          - name: Process each record in the file
            if: ${{ github.event.inputs.selected_options == 'All' }}
            run: |
              file_path="./myfile.txt"

               if [ -f "$file_path" ]; then
               while IFS= read -r line; do
               echo "Processing record: $line"
               done < "$file_path"
               else
               echo "Error: File not found at $file_path"
               exit 1
               fi
          - name: Iterate over One selected options
            if: ${{ github.event.inputs.selected_options != 'All' }}
            run: |
              echo "golu ${{github.event.inputs.selected_options}}"
            



