    name: Testing

    
    on:
      workflow_dispatch:
        inputs:
          selected_options:
            description: 'Choose options to process'
            type: choice
            options:
              - Option A
              - Option B
              - Option C
              - All
            required: true

    jobs:
      loop-through-choices:
        runs-on: ubuntu-latest
        if: ${{github.event.inputs.choice}} == 'All'
        steps:
          - name: Iterate over All selected options
            run: |
              selected_options="optionA,optionB,optionC"
              IFS=',' read -r -a array <<< "$selected_options"
              for item in "${array[@]}"; do
                echo "Processing $item"
                # Perform actions based on the current item
              done

